spring:
  datasource:
    url: jdbc:mysql://localhost:3306/facebook
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql=true:
    properties:
      hibernate:
        format_sql=true:
hibernate:
  use-new-id-generator-mappings: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
